# Development Profile Configuration
server.port=${SERVER_PORT:8081}

# Config Server
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}/nnp-config

# Development Logging
logging.level.com.nnp.haproxy=DEBUG
logging.level.feign=DEBUG
